phases:

# Build all configurations for Windows
- template: /build/ci/phase-template.yml
  parameters:
    name: Windows
    buildScript: build.cmd
    installPython: 1
    buildMatrix:
      Py37:
        _configuration: RlsWinPy3.7
    buildQueue:
      name: Hosted VS2017

# Build all configurations for Mac
- template: /build/ci/phase-template.yml
  parameters:
    name: Mac
    buildScript: ./build.sh
    buildMatrix:
      Py37:
        _configuration: RlsMacPy3.7
        _installpython: 1
    buildQueue:
      name: Hosted macOS

# Build all configurations for Linux
  # Run tests on Ubuntu16
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_Ubuntu16
    buildScript: ./build.sh
    testDistro: ubuntu16
    buildMatrix:
      Py37:
        _configuration: RlsLinPy3.7
        installPython: 1
      Py35:
        _configuration: RlsLinPy3.5
        installPython: 0
    buildQueue:
      name: Hosted Ubuntu 1604
  # Run tests on CentOS7
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_CentOS7
    buildScript: ./build.sh
    testDistro: centos7
    buildMatrix:
      Py37:
        _configuration: RlsLinPy3.7
        installPython: 1
      Py36:
        _configuration: RlsLinPy3.6
        installPython: 0
      Py27:
        _configuration: RlsLinPy2.7
        installPython: 0
    buildQueue:
      name: Hosted Ubuntu 1604